"""fase 2: patient ficha jsonb, wallet as source of truth

Revision ID: 4119623e9546
Revises: 734a4142ec73
Create Date: 2026-07-22 15:16:25.452409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4119623e9546'
down_revision: Union[str, Sequence[str], None] = '734a4142ec73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('ficha', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('patients', sa.Column('ficha_completa_bonus_otorgado', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('patients', sa.Column('onboarding_completado', sa.Boolean(), server_default='false', nullable=False))
    op.drop_column('patients', 'puntos')
    op.drop_column('patients', 'cashback')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('cashback', sa.NUMERIC(precision=12, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False))
    op.add_column('patients', sa.Column('puntos', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_column('patients', 'onboarding_completado')
    op.drop_column('patients', 'ficha_completa_bonus_otorgado')
    op.drop_column('patients', 'ficha')
    # ### end Alembic commands ###
