"""initial schema

Revision ID: 734a4142ec73
Revises: 
Create Date: 2026-07-22 14:26:12.841113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '734a4142ec73'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Required for gen_random_uuid() (pgcrypto) and the appointments
    # anti-double-booking GiST exclude constraint on a uuid column
    # (btree_gist supplies the "=" gist opclass for scalar types).
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('insurers',
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('pais', sa.String(length=2), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('contacto', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plans',
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('esfera', sa.String(length=20), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('precio', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('servicios', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('specialties',
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('icono', sa.String(length=10), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tyc_versions',
    sa.Column('pais', sa.String(length=2), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('publicado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tyc_versions_pais'), 'tyc_versions', ['pais'], unique=False)
    op.create_table('clinics',
    sa.Column('razon_social', sa.String(length=255), nullable=False),
    sa.Column('responsable_sanitario', sa.String(length=255), nullable=True),
    sa.Column('pais', sa.String(length=2), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agreements',
    sa.Column('insurer_id', sa.UUID(), nullable=False),
    sa.Column('vigencia_inicio', sa.Date(), nullable=True),
    sa.Column('vigencia_fin', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['insurer_id'], ['insurers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agreements_clinic_id'), 'agreements', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_agreements_insurer_id'), 'agreements', ['insurer_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('clinic_id', sa.UUID(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('recurso', sa.String(length=255), nullable=False),
    sa.Column('antes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('despues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_clinic_id'), 'audit_logs', ['clinic_id'], unique=False)
    op.create_table('branches',
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('direccion', sa.String(length=500), nullable=True),
    sa.Column('geo', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('horario', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_clinic_id'), 'branches', ['clinic_id'], unique=False)
    op.create_table('catalog_items',
    sa.Column('specialty_id', sa.UUID(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('precio', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('duracion_min', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_items_clinic_id'), 'catalog_items', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_catalog_items_specialty_id'), 'catalog_items', ['specialty_id'], unique=False)
    op.create_table('companies',
    sa.Column('razon_social', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_clinic_id'), 'companies', ['clinic_id'], unique=False)
    op.create_table('integration_configs',
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('credenciales', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_configs_clinic_id'), 'integration_configs', ['clinic_id'], unique=False)
    # TODO (open question, needs a decision before production): once a
    # dedicated least-privilege app DB role exists (distinct from the
    # migration-runner role used here), REVOKE UPDATE, DELETE ON
    # ledger_entries FROM <that role> — belt-and-suspenders immutability
    # beyond the soft-delete listener and "no edit endpoint" in code.
    op.create_table('ledger_entries',
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('moneda', sa.String(length=3), server_default='CLP', nullable=False),
    sa.Column('ref', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_clinic_id'), 'ledger_entries', ['clinic_id'], unique=False)
    op.create_table('patients',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rut', sa.String(length=50), nullable=False),
    sa.Column('direccion', sa.String(length=500), nullable=False),
    sa.Column('nivel', sa.String(length=20), server_default='Bronce', nullable=False),
    sa.Column('puntos', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cashback', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_patients_clinic_id'), 'patients', ['clinic_id'], unique=False)
    op.create_table('promotions',
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descuento', sa.String(length=50), nullable=True),
    sa.Column('vigencia_inicio', sa.Date(), nullable=True),
    sa.Column('vigencia_fin', sa.Date(), nullable=True),
    sa.Column('segmento', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=20), server_default='Borrador', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotions_clinic_id'), 'promotions', ['clinic_id'], unique=False)
    op.create_table('affiliates',
    sa.Column('insurer_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('documento_identidad', sa.String(length=50), nullable=False),
    sa.Column('plan_cobertura', sa.String(length=255), nullable=True),
    sa.Column('vigencia_desde', sa.Date(), nullable=True),
    sa.Column('vigencia_hasta', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['insurer_id'], ['insurers.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliates_insurer_id'), 'affiliates', ['insurer_id'], unique=False)
    op.create_table('agreement_professionals',
    sa.Column('agreement_id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agreement_professionals_agreement_id'), 'agreement_professionals', ['agreement_id'], unique=False)
    op.create_index(op.f('ix_agreement_professionals_clinic_id'), 'agreement_professionals', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_agreement_professionals_professional_id'), 'agreement_professionals', ['professional_id'], unique=False)
    op.create_table('appointments',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=True),
    sa.Column('slot', postgresql.TSTZRANGE(), nullable=False),
    sa.Column('estado', sa.String(length=20), server_default='confirmada', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    postgresql.ExcludeConstraint((sa.column('professional_id'), '='), (sa.column('slot'), '&&'), where=sa.text('deleted_at IS NULL'), using='gist', name='appointments_no_overlap'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['catalog_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_branch_id'), 'appointments', ['branch_id'], unique=False)
    op.create_index(op.f('ix_appointments_clinic_id'), 'appointments', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_professional_id'), 'appointments', ['professional_id'], unique=False)
    op.create_table('aranceles',
    sa.Column('agreement_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('cobertura_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('copago', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['catalog_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aranceles_agreement_id'), 'aranceles', ['agreement_id'], unique=False)
    op.create_index(op.f('ix_aranceles_clinic_id'), 'aranceles', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_aranceles_service_id'), 'aranceles', ['service_id'], unique=False)
    op.create_table('authorizations',
    sa.Column('agreement_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=True),
    sa.Column('estado', sa.String(length=20), server_default='pendiente', nullable=False),
    sa.Column('motivo_rechazo', sa.String(length=500), nullable=True),
    sa.Column('resuelto_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['catalog_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authorizations_agreement_id'), 'authorizations', ['agreement_id'], unique=False)
    op.create_index(op.f('ix_authorizations_clinic_id'), 'authorizations', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_authorizations_patient_id'), 'authorizations', ['patient_id'], unique=False)
    op.create_table('availability_blocks',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('specialty_id', sa.UUID(), nullable=True),
    sa.Column('rango', postgresql.TSTZRANGE(), nullable=False),
    sa.Column('reglas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availability_blocks_branch_id'), 'availability_blocks', ['branch_id'], unique=False)
    op.create_index(op.f('ix_availability_blocks_clinic_id'), 'availability_blocks', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_availability_blocks_professional_id'), 'availability_blocks', ['professional_id'], unique=False)
    op.create_table('company_employees',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('estado', sa.String(length=20), server_default='activo', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_employees_clinic_id'), 'company_employees', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_company_employees_company_id'), 'company_employees', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_employees_patient_id'), 'company_employees', ['patient_id'], unique=False)
    op.create_table('dependents',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('fecha_nac', sa.Date(), nullable=True),
    sa.Column('parentesco', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependents_clinic_id'), 'dependents', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_dependents_patient_id'), 'dependents', ['patient_id'], unique=False)
    op.create_table('emergency_qrs',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('resumen', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_emergency_qrs_clinic_id'), 'emergency_qrs', ['clinic_id'], unique=False)
    op.create_table('exam_orders',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('estado', sa.String(length=20), server_default='pendiente', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_orders_clinic_id'), 'exam_orders', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_exam_orders_patient_id'), 'exam_orders', ['patient_id'], unique=False)
    op.create_index(op.f('ix_exam_orders_professional_id'), 'exam_orders', ['professional_id'], unique=False)
    op.create_table('hospitalizations',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=False),
    sa.Column('centro', sa.String(length=255), nullable=True),
    sa.Column('ingreso', sa.Date(), nullable=True),
    sa.Column('egreso', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospitalizations_clinic_id'), 'hospitalizations', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_hospitalizations_patient_id'), 'hospitalizations', ['patient_id'], unique=False)
    op.create_table('odontograms',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('piezas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_index(op.f('ix_odontograms_clinic_id'), 'odontograms', ['clinic_id'], unique=False)
    op.create_table('payment_splits',
    sa.Column('ledger_entry_id', sa.UUID(), nullable=False),
    sa.Column('beneficiario_id', sa.UUID(), nullable=True),
    sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('regla', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['beneficiario_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ledger_entry_id'], ['ledger_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_splits_clinic_id'), 'payment_splits', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_payment_splits_ledger_entry_id'), 'payment_splits', ['ledger_entry_id'], unique=False)
    op.create_table('role_assignments',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', 'clinic_id', 'branch_id')
    )
    op.create_index(op.f('ix_role_assignments_branch_id'), 'role_assignments', ['branch_id'], unique=False)
    op.create_index(op.f('ix_role_assignments_clinic_id'), 'role_assignments', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_role_assignments_role_id'), 'role_assignments', ['role_id'], unique=False)
    op.create_index(op.f('ix_role_assignments_user_id'), 'role_assignments', ['user_id'], unique=False)
    op.create_table('settlements',
    sa.Column('agreement_id', sa.UUID(), nullable=False),
    sa.Column('periodo', sa.String(length=20), nullable=False),
    sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), server_default='pendiente', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlements_agreement_id'), 'settlements', ['agreement_id'], unique=False)
    op.create_index(op.f('ix_settlements_clinic_id'), 'settlements', ['clinic_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('estado', sa.String(length=20), server_default='activa', nullable=False),
    sa.Column('periodo', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
    op.create_table('tyc_acceptances',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('tyc_version_id', sa.UUID(), nullable=False),
    sa.Column('aceptado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['tyc_version_id'], ['tyc_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tyc_acceptances_patient_id'), 'tyc_acceptances', ['patient_id'], unique=False)
    op.create_index(op.f('ix_tyc_acceptances_tyc_version_id'), 'tyc_acceptances', ['tyc_version_id'], unique=False)
    op.create_table('wallet_accounts',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('puntos', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cashback', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_index(op.f('ix_wallet_accounts_clinic_id'), 'wallet_accounts', ['clinic_id'], unique=False)
    op.create_table('exam_results',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('archivo_url', sa.String(length=1000), nullable=True),
    sa.Column('resultado', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('estado', sa.String(length=20), server_default='en_proceso', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['exam_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_results_clinic_id'), 'exam_results', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_exam_results_order_id'), 'exam_results', ['order_id'], unique=False)
    op.create_table('medical_records',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('contenido', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_records_clinic_id'), 'medical_records', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_medical_records_patient_id'), 'medical_records', ['patient_id'], unique=False)
    op.create_index(op.f('ix_medical_records_professional_id'), 'medical_records', ['professional_id'], unique=False)
    op.create_table('qr_access_logs',
    sa.Column('qr_id', sa.UUID(), nullable=False),
    sa.Column('accedido_por', sa.UUID(), nullable=True),
    sa.Column('profesional_nombre', sa.String(length=255), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['accedido_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['qr_id'], ['emergency_qrs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qr_access_logs_clinic_id'), 'qr_access_logs', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_qr_access_logs_qr_id'), 'qr_access_logs', ['qr_id'], unique=False)
    op.create_table('wallet_transactions',
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('puntos', sa.Integer(), nullable=True),
    sa.Column('cashback', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('ref_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_transactions_clinic_id'), 'wallet_transactions', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_wallet_id'), 'wallet_transactions', ['wallet_id'], unique=False)
    op.create_table('prescriptions',
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('firmado_por', sa.UUID(), nullable=False),
    sa.Column('firmado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.String(length=20), server_default='vigente', nullable=False),
    sa.Column('reemplaza_a', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['firmado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['medical_records.id'], ),
    sa.ForeignKeyConstraint(['reemplaza_a'], ['prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescriptions_clinic_id'), 'prescriptions', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_record_id'), 'prescriptions', ['record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prescriptions_record_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_clinic_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_wallet_transactions_wallet_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_clinic_id'), table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_index(op.f('ix_qr_access_logs_qr_id'), table_name='qr_access_logs')
    op.drop_index(op.f('ix_qr_access_logs_clinic_id'), table_name='qr_access_logs')
    op.drop_table('qr_access_logs')
    op.drop_index(op.f('ix_medical_records_professional_id'), table_name='medical_records')
    op.drop_index(op.f('ix_medical_records_patient_id'), table_name='medical_records')
    op.drop_index(op.f('ix_medical_records_clinic_id'), table_name='medical_records')
    op.drop_table('medical_records')
    op.drop_index(op.f('ix_exam_results_order_id'), table_name='exam_results')
    op.drop_index(op.f('ix_exam_results_clinic_id'), table_name='exam_results')
    op.drop_table('exam_results')
    op.drop_index(op.f('ix_wallet_accounts_clinic_id'), table_name='wallet_accounts')
    op.drop_table('wallet_accounts')
    op.drop_index(op.f('ix_tyc_acceptances_tyc_version_id'), table_name='tyc_acceptances')
    op.drop_index(op.f('ix_tyc_acceptances_patient_id'), table_name='tyc_acceptances')
    op.drop_table('tyc_acceptances')
    op.drop_index(op.f('ix_subscriptions_plan_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_settlements_clinic_id'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_agreement_id'), table_name='settlements')
    op.drop_table('settlements')
    op.drop_index(op.f('ix_role_assignments_user_id'), table_name='role_assignments')
    op.drop_index(op.f('ix_role_assignments_role_id'), table_name='role_assignments')
    op.drop_index(op.f('ix_role_assignments_clinic_id'), table_name='role_assignments')
    op.drop_index(op.f('ix_role_assignments_branch_id'), table_name='role_assignments')
    op.drop_table('role_assignments')
    op.drop_index(op.f('ix_payment_splits_ledger_entry_id'), table_name='payment_splits')
    op.drop_index(op.f('ix_payment_splits_clinic_id'), table_name='payment_splits')
    op.drop_table('payment_splits')
    op.drop_index(op.f('ix_odontograms_clinic_id'), table_name='odontograms')
    op.drop_table('odontograms')
    op.drop_index(op.f('ix_hospitalizations_patient_id'), table_name='hospitalizations')
    op.drop_index(op.f('ix_hospitalizations_clinic_id'), table_name='hospitalizations')
    op.drop_table('hospitalizations')
    op.drop_index(op.f('ix_exam_orders_professional_id'), table_name='exam_orders')
    op.drop_index(op.f('ix_exam_orders_patient_id'), table_name='exam_orders')
    op.drop_index(op.f('ix_exam_orders_clinic_id'), table_name='exam_orders')
    op.drop_table('exam_orders')
    op.drop_index(op.f('ix_emergency_qrs_clinic_id'), table_name='emergency_qrs')
    op.drop_table('emergency_qrs')
    op.drop_index(op.f('ix_dependents_patient_id'), table_name='dependents')
    op.drop_index(op.f('ix_dependents_clinic_id'), table_name='dependents')
    op.drop_table('dependents')
    op.drop_index(op.f('ix_company_employees_patient_id'), table_name='company_employees')
    op.drop_index(op.f('ix_company_employees_company_id'), table_name='company_employees')
    op.drop_index(op.f('ix_company_employees_clinic_id'), table_name='company_employees')
    op.drop_table('company_employees')
    op.drop_index(op.f('ix_availability_blocks_professional_id'), table_name='availability_blocks')
    op.drop_index(op.f('ix_availability_blocks_clinic_id'), table_name='availability_blocks')
    op.drop_index(op.f('ix_availability_blocks_branch_id'), table_name='availability_blocks')
    op.drop_table('availability_blocks')
    op.drop_index(op.f('ix_authorizations_patient_id'), table_name='authorizations')
    op.drop_index(op.f('ix_authorizations_clinic_id'), table_name='authorizations')
    op.drop_index(op.f('ix_authorizations_agreement_id'), table_name='authorizations')
    op.drop_table('authorizations')
    op.drop_index(op.f('ix_aranceles_service_id'), table_name='aranceles')
    op.drop_index(op.f('ix_aranceles_clinic_id'), table_name='aranceles')
    op.drop_index(op.f('ix_aranceles_agreement_id'), table_name='aranceles')
    op.drop_table('aranceles')
    op.drop_index(op.f('ix_appointments_professional_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_clinic_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_branch_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_agreement_professionals_professional_id'), table_name='agreement_professionals')
    op.drop_index(op.f('ix_agreement_professionals_clinic_id'), table_name='agreement_professionals')
    op.drop_index(op.f('ix_agreement_professionals_agreement_id'), table_name='agreement_professionals')
    op.drop_table('agreement_professionals')
    op.drop_index(op.f('ix_affiliates_insurer_id'), table_name='affiliates')
    op.drop_table('affiliates')
    op.drop_index(op.f('ix_promotions_clinic_id'), table_name='promotions')
    op.drop_table('promotions')
    op.drop_index(op.f('ix_patients_clinic_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_ledger_entries_clinic_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_integration_configs_clinic_id'), table_name='integration_configs')
    op.drop_table('integration_configs')
    op.drop_index(op.f('ix_companies_clinic_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_catalog_items_specialty_id'), table_name='catalog_items')
    op.drop_index(op.f('ix_catalog_items_clinic_id'), table_name='catalog_items')
    op.drop_table('catalog_items')
    op.drop_index(op.f('ix_branches_clinic_id'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_audit_logs_clinic_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_agreements_insurer_id'), table_name='agreements')
    op.drop_index(op.f('ix_agreements_clinic_id'), table_name='agreements')
    op.drop_table('agreements')
    op.drop_table('clinics')
    op.drop_index(op.f('ix_tyc_versions_pais'), table_name='tyc_versions')
    op.drop_table('tyc_versions')
    op.drop_table('specialties')
    op.drop_table('roles')
    op.drop_table('plans')
    op.drop_table('insurers')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')

    op.execute("DROP EXTENSION IF EXISTS btree_gist")
    op.execute("DROP EXTENSION IF EXISTS pgcrypto")
    # ### end Alembic commands ###
